---
resource_types:
- name: cycloid-events
  type: docker-image
  source:
    repository: cycloid/cycloid-events-resource
    tag: latest

resources:
- name: cycloid-events
  type: cycloid-events
  source:
    api_url: https://http-api.cycloid.io
    api_login: <your email>
    api_password: <your password>
    organization: <your organization>
    # All params can be setted as a default in the source
    tags:
      - key: env
        value: production

jobs:
- name: test
  plan:
    - put: cycloid-events
      params:
        icon: fa-code-branch
        title: Production deployment 1
        message: A new deployment has been done on the production environment
        severity: info
        type: Custom
